# Generated by Django 5.1.5 on 2025-01-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_leaderboard_profile_country_wpm"),
    ]

    operations = [
        migrations.DeleteModel(
            name="leaderboard",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.DeleteModel(
            name="wpm",
        ),
    ]
