# Generated by Django 5.1.5 on 2025-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="duration",
            field=models.IntegerField(
                choices=[(3, "3 seconds"), (15, "15 seconds"), (30, "30 seconds")]
            ),
        ),
    ]
