# Generated by Django 5.1.5 on 2025-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_test_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="max_wpm_15",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_wpm_30",
            field=models.FloatField(default=0),
        ),
    ]
