# Generated by Django 5.1.5 on 2025-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_test_duration_league_leaguemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="code",
            field=models.CharField(default="7163F8", max_length=8, unique=True),
        ),
    ]
